services:

  postgres:
    image: postgres:16
    container_name: ocp_postgres
    restart: always

    environment:
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d industrial_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ocp_pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ocp.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

  data-generator:
    build:
      context: .
      dockerfile: docker/data-generator/Dockerfile

    container_name: industrial_data_generator

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    depends_on:
      postgres:
        condition: service_healthy

    profiles:
      - tools

  spark-batch:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_batch

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      BRONZE_PATH: /opt/spark-data/bronze

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data

    depends_on:
      postgres:
        condition: service_healthy

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2,org.postgresql:postgresql:42.7.5
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/ingest_postgres_bronze.py

    profiles:
      - batch

volumes:
  postgres_data:
