services:

  postgres:
    image: postgres:16
    container_name: ocp_postgres
    restart: always

    environment:
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d industrial_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ocp_pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ocp.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

  data-generator:
    build:
      context: .
      dockerfile: docker/data-generator/Dockerfile

    container_name: industrial_data_generator

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    depends_on:
      postgres:
        condition: service_healthy

    profiles:
      - tools

  spark-batch:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_batch

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      BRONZE_PATH: /opt/spark-data/bronze

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    depends_on:
      postgres:
        condition: service_healthy

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2,org.postgresql:postgresql:42.7.5
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/ingest_postgres_bronze.py

    profiles:
      - batch

  spark-silver:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_silver

    environment:
      BRONZE_PATH: /opt/spark-data/bronze
      SILVER_PATH: /opt/spark-data/silver

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/transform_bronze_silver.py

    profiles:
      - silver

  spark-gold:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_gold

    environment:
      SILVER_PATH: /opt/spark-data/silver
      GOLD_PATH: /opt/spark-data/gold

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/transform_silver_gold.py

    profiles:
      - gold

  spark-validate-gold:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_validate_gold

    environment:
      GOLD_PATH: /opt/spark-data/gold

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/validate_gold.py

    profiles:
      - validation

  kafka:
    image: apache/kafka:4.1.2
    container_name: industrial_kafka
    hostname: kafka
    restart: unless-stopped

    ports:
      - "29092:29092"

    environment:
      # Identité du nœud Kafka
      KAFKA_NODE_ID: 1

      # Mode KRaft : ce nœud est broker et contrôleur
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners disponibles dans le conteneur
      KAFKA_LISTENERS: >-
        PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093, PLAINTEXT_HOST://0.0.0.0:29092

      # Adresse utilisée par les autres conteneurs et par Windows
      KAFKA_ADVERTISED_LISTENERS: >-
        PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        CONTROLLER:PLAINTEXT, PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Configuration du contrôleur KRaft
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Configuration adaptée à un cluster local à un seul nœud
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      # Identifiant stable du cluster local
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 20s

    profiles:
      - streaming

  sensor-producer:
    build:
      context: .
      dockerfile: docker/kafka-producer/Dockerfile

    container_name: industrial_sensor_producer

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: industrial-sensor-readings
      EVENT_INTERVAL_SECONDS: 1

    depends_on:
      kafka:
        condition: service_healthy

    restart: unless-stopped

    profiles:
      - streaming

  spark-streaming:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_streaming

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: industrial-sensor-readings
      STREAMING_BRONZE_PATH: >-
        /opt/spark-data/bronze_streaming/sensor_readings
      STREAMING_CHECKPOINT_PATH: >-
        /opt/spark-data/checkpoints/kafka_sensor_bronze

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    depends_on:
      kafka:
        condition: service_healthy

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --repositories
      - https://repo.maven.apache.org/maven2
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6,io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/stream_kafka_bronze.py

    restart: unless-stopped

    profiles:
      - streaming

  spark-streaming-silver:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_streaming_silver

    environment:
      STREAMING_BRONZE_PATH: >-
        /opt/spark-data/bronze_streaming/sensor_readings
      STREAMING_SILVER_PATH: >-
        /opt/spark-data/silver_streaming/sensor_readings
      STREAMING_SILVER_CHECKPOINT_PATH: >-
        /opt/spark-data/checkpoints/kafka_sensor_silver

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/transform_streaming_bronze_silver.py

    restart: unless-stopped

    profiles:
      - streaming

  spark-validate-streaming:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_validate_streaming

    environment:
      STREAMING_BRONZE_PATH: >-
        /opt/spark-data/bronze_streaming/sensor_readings

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/validate_streaming_bronze.py

    profiles:
      - streaming


  spark-publish-gold:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: industrial_spark_publish_gold

    environment:
      GOLD_PATH: /opt/spark-data/gold
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: industrial_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      ANALYTICS_SCHEMA: analytics

    volumes:
      - ./spark:/opt/spark/work-dir/spark
      - ./data:/opt/spark-data
      - spark_ivy_cache:/home/spark/.ivy2

    depends_on:
      postgres:
        condition: service_healthy

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - local[*]
      - --packages
      - io.delta:delta-spark_2.12:3.3.2,org.postgresql:postgresql:42.7.5
      - --conf
      - spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
      - --conf
      - spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - /opt/spark/work-dir/spark/jobs/publish_gold_postgres.py

    profiles:
      - serving

volumes:
  postgres_data:
  spark_ivy_cache:
  kafka_data:
